In [2]:
# numpy(numerical python)
# 다차원 배열 처리. 파이썬 데이터 분석 패키지
# 배열 차원 rank, 배열 크기 shape
# import numpy as np

In [3]:
# 주요 함수
# numpy.abs(array)
# numpy.sqrt(array) : 제곱근(루트)
# numpy.square(array) : 제곱
# numpy.exp(array) : 지수
# numpy.Log(array)
# numpy.add(array1, array2) : 두 배열 덧셈
# numpy.subtract(array1, array2) : 배열1 - 배열2
# numpy.multiply(array1, array2) : 배열1 * 배열2

In [4]:
# numpy 배열 기본
import numpy as np
v1 = np.array([1, 2, 3, 4]) # 괄호 안에는 리스트 형태로 데이터 입력
print(v1)

[1 2 3 4]


In [6]:
# np.arange(시작 값, 끝 값, 간격)
# np.arange(끝 값)
# 연속되거나 일정한 규칙을 가진 숫자
v1 = np.arange(5)
print(v1)

# 연속되거나 일정한 규칙을 가진 숫자, 데이터 형태 지정
v2 = np.arange(1, 10, 2, dtype=int)
v3 = np.arange(3.5, 10.5, 2, dtype=float)
print(v2)
print(v3)

# 제곱값 생성
v4 = np.arange(1, 10, 2)**2
print(v4)

# 세제곱값 생성
v5 = np.arange(1, 10, 2)**3
print(v5)

[0 1 2 3 4]
[1 3 5 7 9]
[3.5 5.5 7.5 9.5]
[ 1  9 25 49 81]
[  1  27 125 343 729]


In [8]:
# array는 입력받은 배열 그대로 numpy.ndarray를 만들고 arange는 범위 안의 요소로 numpy.ndarray를 만듦
array1 = np.array([1,2,3,4,5])
array2 = np.arange(1,6)
print(array1)
print(array2)

[1 2 3 4 5]
[1 2 3 4 5]


In [10]:
# 행렬 만들기
# np.reshape(차원, 행, 열, oreder='C' 또는 'F') C는 행 순서 F는 열 순서
v1 = np.arange(12)
print(v1)
v2 = v1.reshape(2, 6)
print(v2)
v3 = v1.reshape(2, 6, order='F')
print(v3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [11]:
# 행렬 계산
v1 = np.arange(1, 5).reshape(2, 2)

# v1 = [[1, 2]
#      [3, 4]]

print(np.add(v1, v1)) # 덧셈
print(np.subtract(v1, v1)) # 뺄셈
print(np.multiply(v1, v1)) # 곱셈
print(np.dot(v1, v1)) # 행렬 연산

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [12]:
# 다차원 행렬 만들기
v1 = np.arange(12)
print(v1)
v2 = v1.reshape(2, 3, 2, order='F')
print(v2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [14]:
# 다차원 배열에서 요소의 최대값 및 최소값 반환
v3 = np.arange(3.5, 10.5, 2, dtype=float)
print(v3)
v4 = np.arange(1, 5).reshape(2, 2)
print(v4)
print(np.amax(v3)) # 최대값 확인
print(np.amin(v4)) # 최소값 확인
print(v3.dtype) # 데이터 타입 확인
print(v4.shape) # 행, 열, 차원 확인

[3.5 5.5 7.5 9.5]
[[1 2]
 [3 4]]
9.5
1
float64
(2, 2)
